show:
    path: /alerts/{identity}
    controller: App\Presentation\Web\Controller\AlertController::showAction
    methods: [GET]
search:
    path: /alerts
    controller: App\Presentation\Web\Controller\AlertController::searchAction
    methods: [GET]
report:
    path: /alerts
    controller: App\Presentation\Web\Controller\AlertController::reportAction
    methods: [POST]

confirm:
    path: /alerts/{identity}
    controller: App\Presentation\Web\Controller\AlertController::confirmAction
    methods: [POST]