search:
    path: /alerts
    controller: App\Presentation\Web\Controller\AlertController::searchAction
    methods: [GET]
report:
    path: /alerts
    controller: App\Presentation\Web\Controller\AlertController::reportAction
    methods: [POST]